platform :ios, '8.0'

target 'DMPasscode' do
  pod "DMPasscode", :path => "../"
end

target 'Tests' do
  pod "DMPasscode", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
